# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.4
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build:
    docker:
      - image: cimg/node:17.4.0-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: BackEnd Install Dependencies
          command: |
            npm run backend:install
      - run:
          name: FrontEnd Install Dependencies
          command: |
            npm run frontend:install
      - run:
          name: FrontEnd Test Application
          command: |
            npm run frontend:test
      - run:
          name: BackEnd Build
          command: |
            npm run backend:build
      - run:
          name: FrontEnd Build
          command: |
            npm run frontend:build
      - run:
          name: Deploy Backend App
          command: |
            npm run backend:deploy
      - run:
          name: Deploy FrontEnd App
          command: |
            npm run frontend:deploy
workflows:
  Udagram:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master